#!/usr/bin/python3
# -*- coding: utf-8 -*-

class Game:
    def aiMove(self, depth: int) -> int: ...
    def humanMove(self, col: int) -> int: ...
    def resetBoard(self) -> None: ...
    def printBoard(self) -> None: ...
    def run(self) -> None: ...
    def count(self) -> int: ...
