#!/usr/bin/python3
# -*- coding: utf-8 -*-

class Game:
    def aiMove(depth: int) -> int: ...
    def humanMove(col: int) -> int: ...
    def clearBoard() -> None: ...
    def printBoard() -> None: ...
    def run() -> None: ...
