#!/usr/bin/python3
# -*- coding: utf-8 -*-

class Game:
    def aiMove(depth: int) -> int: ...
    def humanMove(col: int) -> int: ...
    def resetBoard() -> None: ...
    def printBoard() -> None: ...
    def run() -> None: ...
    def get_count() -> int: ...
    def human_winning() -> bool: ...
    def ai_winning() -> bool: ...
    def draw() -> int: ...
    def forceAIMove(col: int) -> int: ...
    def scoreAIpos() -> int: ...
